name: app_cas_natal
description: "Plataforma de cursos EAD do CAS Natal/RN"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  http: ^1.5.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  image_picker: ^1.2.1
  flutter_staggered_grid_view: ^0.7.0
  youtube_player_iframe: ^5.2.2
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_cas.png
    - assets/logos/logo_cas_transparente.png
    - assets/logos/logo_cas_transparente2.png
    - assets/logos/google_logo.png

    - assets/avatar/menina.png
    - assets/avatar/menino.png
    - assets/avatar/menina2.png
    - assets/avatar/menino2.png

    - assets/modulos/diversidade.jpg
    - assets/modulos/letramento.png
    - assets/modulos/inclusao.jpg
    - assets/modulos/placeholder_curso.jpg
    - assets/placeholder.png
    
    - assets/storybook/cas.jpg
    - assets/storybook/capa.png
    - assets/storybook/foto0.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_cas.png"

flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  image: assets/icon_cas.png
